-- ============================================
-- PERSONAL LEARNING SYSTEM - POSTGRESQL SCHEMA (SUPABASE)
-- ============================================

-- Core Profile: The evolving digital you
CREATE TABLE IF NOT EXISTS profile (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    total_responses INTEGER DEFAULT 0,
    engagement_score REAL DEFAULT 0.0,
    learning_version INTEGER DEFAULT 1,
    metadata JSONB
);

-- Dimensions: Categories for multi-dimensional analysis
CREATE TABLE IF NOT EXISTS dimensions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) UNIQUE NOT NULL,
    parent_dimension_id BIGINT REFERENCES dimensions(id),
    weight REAL DEFAULT 1.0,
    description TEXT,
    metadata JSONB
);

-- Aspects: Granular aspects within dimensions
CREATE TABLE IF NOT EXISTS aspects (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dimension_id BIGINT REFERENCES dimensions(id),
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    metadata JSONB,
    UNIQUE(dimension_id, name)
);

-- Contexts: Environmental and situational factors
CREATE TABLE IF NOT EXISTS contexts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    context_type VARCHAR(50) NOT NULL,
    key VARCHAR(100) NOT NULL,
    value VARCHAR(255),
    metadata JSONB,
    UNIQUE(context_type, key, value)
);

-- Questions: The question bank with multi-dimensional tags
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL UNIQUE,
    question_type VARCHAR(50),
    difficulty_level INTEGER DEFAULT 1,
    engagement_factor REAL DEFAULT 1.0,
    primary_dimension_id BIGINT REFERENCES dimensions(id),
    metadata JSONB,
    active BOOLEAN DEFAULT TRUE,
    times_asked INTEGER DEFAULT 0,
    avg_response_time REAL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Question Dimensions: Multi-dimensional question mapping
CREATE TABLE IF NOT EXISTS question_dimensions (
    question_id BIGINT REFERENCES questions(id),
    dimension_id BIGINT REFERENCES dimensions(id),
    weight REAL DEFAULT 1.0,
    PRIMARY KEY (question_id, dimension_id)
);

-- Question Aspects: What aspects does this question measure
CREATE TABLE IF NOT EXISTS question_aspects (
    question_id BIGINT REFERENCES questions(id),
    aspect_id BIGINT REFERENCES aspects(id),
    weight REAL DEFAULT 1.0,
    PRIMARY KEY (question_id, aspect_id)
);

-- Answer Options: Possible responses to questions
CREATE TABLE IF NOT EXISTS answer_options (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT REFERENCES questions(id),
    text VARCHAR(255) NOT NULL,
    option_order INTEGER,
    aspect_id BIGINT REFERENCES aspects(id),
    weight REAL DEFAULT 1.0,
    metadata JSONB
);

-- Responses: User answers - the core dataset
CREATE TABLE IF NOT EXISTS responses (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT REFERENCES profile(id),
    question_id BIGINT REFERENCES questions(id),
    answer_option_id BIGINT REFERENCES answer_options(id),
    response_type VARCHAR(20),
    response_time_ms INTEGER,
    confidence_level REAL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    session_id VARCHAR(100),
    metadata JSONB
);

-- Response Contexts: What context was the response made in
CREATE TABLE IF NOT EXISTS response_contexts (
    response_id BIGINT REFERENCES responses(id),
    context_id BIGINT REFERENCES contexts(id),
    PRIMARY KEY (response_id, context_id)
);

-- Patterns: Detected patterns from responses
CREATE TABLE IF NOT EXISTS patterns (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT REFERENCES profile(id),
    pattern_type VARCHAR(50),
    dimension_id BIGINT REFERENCES dimensions(id),
    aspect_id BIGINT REFERENCES aspects(id),
    confidence REAL,
    strength REAL,
    evidence_count INTEGER,
    first_detected TIMESTAMPTZ,
    last_updated TIMESTAMPTZ,
    metadata JSONB
);

-- Ensure uniqueness for patterns with dimensions/aspects
CREATE UNIQUE INDEX IF NOT EXISTS idx_patterns_unique_aspect
ON patterns(profile_id, dimension_id, aspect_id)
WHERE dimension_id IS NOT NULL AND aspect_id IS NOT NULL;

-- Ensure uniqueness for general patterns (like meeting_density)
CREATE UNIQUE INDEX IF NOT EXISTS idx_patterns_unique_type
ON patterns(profile_id, pattern_type)
WHERE dimension_id IS NULL AND aspect_id IS NULL;

-- Relationships: People, projects, entities
CREATE TABLE IF NOT EXISTS entities (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR(50),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    metadata JSONB,
    UNIQUE(name, entity_type)
);

-- Entity Attributes: How you feel/think about entities
CREATE TABLE IF NOT EXISTS entity_attributes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT REFERENCES profile(id),
    entity_id BIGINT REFERENCES entities(id),
    attribute_type VARCHAR(50),
    aspect_id BIGINT REFERENCES aspects(id),
    value REAL,
    text_value VARCHAR(255),
    confidence REAL,
    last_updated TIMESTAMPTZ,
    metadata JSONB
);

-- Workflows: Task pipelines and methodologies
CREATE TABLE IF NOT EXISTS workflows (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    workflow_type VARCHAR(50),
    status VARCHAR(50),
    created_from_responses BOOLEAN DEFAULT FALSE,
    metadata JSONB
);

-- Workflow Steps: Specific actions in workflows
CREATE TABLE IF NOT EXISTS workflow_steps (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow_id BIGINT REFERENCES workflows(id),
    step_order INTEGER,
    description TEXT,
    status VARCHAR(50),
    due_date TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    metadata JSONB
);

-- Recommendations: Generated suggestions
CREATE TABLE IF NOT EXISTS recommendations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT REFERENCES profile(id),
    recommendation_type VARCHAR(50),
    title VARCHAR(255),
    description TEXT,
    priority REAL,
    confidence REAL,
    based_on_pattern_ids JSONB,
    status VARCHAR(50),
    created_at TIMESTAMPTZ,
    responded_at TIMESTAMPTZ,
    metadata JSONB
);

-- Datasets: Custom user datasets
CREATE TABLE IF NOT EXISTS datasets (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT REFERENCES profile(id),
    name VARCHAR(255) NOT NULL,
    dataset_type VARCHAR(50),
    description TEXT,
    schema_definition JSONB,
    row_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    metadata JSONB
);

-- Dataset Records: Actual data rows
CREATE TABLE IF NOT EXISTS dataset_records (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_id BIGINT REFERENCES datasets(id),
    record_data JSONB,
    created_at TIMESTAMPTZ,
    metadata JSONB
);

-- Learning Snapshots: Periodic captures of learned state
CREATE TABLE IF NOT EXISTS learning_snapshots (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id BIGINT REFERENCES profile(id),
    snapshot_date TIMESTAMPTZ,
    total_responses INTEGER,
    pattern_count INTEGER,
    top_patterns JSONB,
    profile_state JSONB,
    insights JSONB,
    metadata JSONB
);

-- INDEXES for Performance
CREATE INDEX IF NOT EXISTS idx_responses_profile ON responses(profile_id);
CREATE INDEX IF NOT EXISTS idx_responses_question ON responses(question_id);
CREATE INDEX IF NOT EXISTS idx_responses_created ON responses(created_at);
CREATE INDEX IF NOT EXISTS idx_responses_session ON responses(session_id);
CREATE INDEX IF NOT EXISTS idx_patterns_profile ON patterns(profile_id);
CREATE INDEX IF NOT EXISTS idx_patterns_dimension ON patterns(dimension_id);
CREATE INDEX IF NOT EXISTS idx_patterns_aspect ON patterns(aspect_id);
CREATE INDEX IF NOT EXISTS idx_patterns_confidence ON patterns(confidence);
CREATE INDEX IF NOT EXISTS idx_entity_attrs_profile ON entity_attributes(profile_id);
CREATE INDEX IF NOT EXISTS idx_entity_attrs_entity ON entity_attributes(entity_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_profile ON recommendations(profile_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_status ON recommendations(status);
